# -*- coding: utf-8 -*-

import json
import argparse
from pathlib import Path
from datetime import datetime, timedelta

import numpy as np
import pandas as pd
import yfinance as yf


BASE_DIR = Path(__file__).resolve().parent

# ==============================
# CONFIG (核心可調參數)
# ==============================
LOOKBACK_CALENDAR_DAYS = 120      # 往前抓多少日曆天
MIN_TRADING_DAYS = 25             # 最低可產生 Phi–π 的交易日數
IDEAL_TRADING_DAYS = 45           # 高可信度門檻


# ==============================
# Utils
# ==============================

def safe_scalar(x):
    """強制轉為 python scalar"""
    try:
        return float(x)
    except Exception:
        return None


def nearest_trading_day(index: pd.DatetimeIndex, target: pd.Timestamp):
    """回傳 <= target 的最近交易日"""
    pos = index.searchsorted(target, side="right") - 1
    if pos < 0:
        return None
    return index[pos]


def compute_breath(close: pd.Series):
    if close.empty:
        return None
    hi = safe_scalar(close.max())
    lo = safe_scalar(close.min())
    if hi is None or lo is None or lo <= 0:
        return None
    return hi / lo


# ==============================
# Core
# ==============================

def generate_phi_pi_for_market(market: str, signal_date: pd.Timestamp):
    start = signal_date - timedelta(days=LOOKBACK_CALENDAR_DAYS)

    try:
        df = yf.download(
            market,
            start=start,
            end=signal_date + timedelta(days=1),
            auto_adjust=False,
            progress=False,
        )
    except Exception as e:
        return None, f"download failed: {e}"

    if df is None or df.empty:
        return None, "no price data"

    # MultiIndex 防呆
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    if "Close" not in df.columns:
        return None, "no Close column"

    close = df["Close"].dropna()
    if len(close) < MIN_TRADING_DAYS:
        return None, "not enough trading days"

    # 對齊實際交易日
    entry_day = nearest_trading_day(close.index, signal_date)
    if entry_day is None:
        return None, "no valid trading day"

    last_price = safe_scalar(close.loc[entry_day])
    prev_price = safe_scalar(close.iloc[-2]) if len(close) >= 2 else None

    if last_price is None or prev_price is None:
        return None, "invalid price"

    breath = compute_breath(close)

    confidence = (
        "high" if len(close) >= IDEAL_TRADING_DAYS else "low"
    )

    result = {
        "market": market,
        "signal_date": signal_date.strftime("%Y-%m-%d"),
        "entry_price": last_price,
        "prev_price": prev_price,
        "trading_days": len(close),
        "confidence": confidence,
        "breath_value": breath,
        "notes": "auto-generated by Phi–π batch engine",
    }

    return result, None


# ==============================
# Main
# ==============================

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", required=True, help="Signal date YYYY-MM-DD")
    args = parser.parse_args()

    signal_date = pd.to_datetime(args.date)

    markets_file = BASE_DIR / "markets.txt"
    if not markets_file.exists():
        raise FileNotFoundError("markets.txt not found")

    markets = [
        m.strip()
        for m in markets_file.read_text(encoding="utf-8").splitlines()
        if m.strip()
    ]

    output_dir = BASE_DIR / "output" / "phi_pi" / "daily" / args.date
    output_dir.mkdir(parents=True, exist_ok=True)

    success = 0
    failed = []

    print("\n[INFO] Phi–π Historical Batch")
    print(f"[INFO] Signal date : {args.date}")
    print(f"[INFO] Output dir  : {output_dir}\n")

    for m in markets:
        print(f"▶ {m}")
        result, err = generate_phi_pi_for_market(m, signal_date)
        if err:
            print(f"❌ {err}")
            failed.append(m)
            continue

        out_file = output_dir / f"phi_pi_daily_{m}.json"
        with open(out_file, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)

        print(f"✅ OK | trading_days={result['trading_days']} | confidence={result['confidence']}")
        success += 1

    print("\n=== BATCH SUMMARY ===")
    print(f"Success : {success}")
    print(f"Failed  : {len(failed)}")
    if failed:
        print("Failed markets:")
        for m in failed:
            print(f"  - {m}")


if __name__ == "__main__":
    main()
