# -*- coding: utf-8 -*-

import json
import argparse
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent


# --------------------------------------------------
# Utils
# --------------------------------------------------

def load_daily_phi_pi(daily_dir: Path):
    """
    載入單一日期資料夾內所有 phi_pi_daily_*.json
    """
    if not daily_dir.exists():
        return []

    items = []
    for p in daily_dir.glob("phi_pi_daily_*.json"):
        try:
            with open(p, "r", encoding="utf-8") as f:
                data = json.load(f)
                items.append(data)
        except Exception:
            continue

    return items


def resolve_daily_dir(target_date: str):
    """
    嚴格指定歷史日期：
    output/phi_pi/daily/YYYY-MM-DD
    """
    daily_dir = BASE_DIR / "output" / "phi_pi" / "daily" / target_date
    if not daily_dir.exists():
        raise FileNotFoundError(
            f"Daily phi-pi folder not found: {daily_dir}"
        )
    return daily_dir


def ensure_output_dir(target_date: str):
    out_dir = BASE_DIR / "output" / "option" / target_date
    out_dir.mkdir(parents=True, exist_ok=True)
    return out_dir


# --------------------------------------------------
# Signal Builder
# --------------------------------------------------

def build_option_signals(daily_items, signal_date: str):
    signals = []

    for d in daily_items:
        market = d.get("market")
        breath = d.get("breath_value")
        gap = d.get("gap_direction")

        if market is None or breath is None:
            continue

        # 基本門檻（保持你原系統邏輯）
        if breath < 1.0:
            continue

        signal = {
            "market": market,
            "date": signal_date,
            "dte": 21,
            "breath_value": round(breath, 6),
            "vol_state": d.get("vol_state"),
            "gap_direction": gap,
            "regime": d.get("regime"),
            "notes": "auto-generated by build_phi_pi_option_signals (historical-safe)",
        }

        signals.append(signal)

    return signals


# --------------------------------------------------
# Main
# --------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--date",
        required=True,
        help="Signal date YYYY-MM-DD (must exist in output/phi_pi/daily)",
    )
    args = parser.parse_args()

    # 驗證日期格式
    try:
        datetime.strptime(args.date, "%Y-%m-%d")
    except ValueError:
        raise ValueError("Date format must be YYYY-MM-DD")

    # --------------------------------------------------
    # Resolve daily source (嚴格歷史)
    # --------------------------------------------------
    daily_dir = resolve_daily_dir(args.date)
    print(f"[INFO] Build option signals from: {daily_dir}")

    daily_items = load_daily_phi_pi(daily_dir)
    if not daily_items:
        print("[WARN] No daily phi-pi files found.")
        return

    # --------------------------------------------------
    # Build signals
    # --------------------------------------------------
    signals = build_option_signals(daily_items, args.date)

    out_dir = ensure_output_dir(args.date)
    out_path = out_dir / "phi_pi_option_signals.json"

    payload = {
        "date": args.date,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "signal_count": len(signals),
        "signals": signals,
    }

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    print(f"[OK] Option signals generated → {out_path}")
    print(f"[INFO] Signals count: {len(signals)}")


if __name__ == "__main__":
    main()
